// source: policy_error_details.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = globalThis;

var rpc_policy_pb = require('./rpc_policy_pb.js');
goog.object.extend(proto, rpc_policy_pb);
goog.exportSymbol('proto.pb.PolicyAcceptanceRequired', null, global);
goog.exportSymbol('proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.PolicyAcceptanceRequired = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pb.PolicyAcceptanceRequired.repeatedFields_, null);
};
goog.inherits(proto.pb.PolicyAcceptanceRequired, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.PolicyAcceptanceRequired.displayName = 'proto.pb.PolicyAcceptanceRequired';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.displayName = 'proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pb.PolicyAcceptanceRequired.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.PolicyAcceptanceRequired.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.PolicyAcceptanceRequired.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.PolicyAcceptanceRequired} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.PolicyAcceptanceRequired.toObject = function(includeInstance, msg) {
  var f, obj = {
requiredPoliciesList: jspb.Message.toObjectList(msg.getRequiredPoliciesList(),
    proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.PolicyAcceptanceRequired}
 */
proto.pb.PolicyAcceptanceRequired.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.PolicyAcceptanceRequired;
  return proto.pb.PolicyAcceptanceRequired.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.PolicyAcceptanceRequired} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.PolicyAcceptanceRequired}
 */
proto.pb.PolicyAcceptanceRequired.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo;
      reader.readMessage(value,proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.deserializeBinaryFromReader);
      msg.addRequiredPolicies(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.PolicyAcceptanceRequired.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.PolicyAcceptanceRequired.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.PolicyAcceptanceRequired} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.PolicyAcceptanceRequired.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequiredPoliciesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
policyType: jspb.Message.getFieldWithDefault(msg, 1, 0),
version: jspb.Message.getFieldWithDefault(msg, 2, ""),
policyVersionId: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo}
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo;
  return proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo}
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.pb.PolicyType} */ (reader.readEnum());
      msg.setPolicyType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setVersion(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPolicyVersionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPolicyType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPolicyVersionId();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional PolicyType policy_type = 1;
 * @return {!proto.pb.PolicyType}
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.prototype.getPolicyType = function() {
  return /** @type {!proto.pb.PolicyType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.pb.PolicyType} value
 * @return {!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo} returns this
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.prototype.setPolicyType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string version = 2;
 * @return {string}
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.prototype.getVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo} returns this
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.prototype.setVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 policy_version_id = 3;
 * @return {number}
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.prototype.getPolicyVersionId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo} returns this
 */
proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo.prototype.setPolicyVersionId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated RequiredPolicyInfo required_policies = 1;
 * @return {!Array<!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo>}
 */
proto.pb.PolicyAcceptanceRequired.prototype.getRequiredPoliciesList = function() {
  return /** @type{!Array<!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo, 1));
};


/**
 * @param {!Array<!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo>} value
 * @return {!proto.pb.PolicyAcceptanceRequired} returns this
*/
proto.pb.PolicyAcceptanceRequired.prototype.setRequiredPoliciesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo}
 */
proto.pb.PolicyAcceptanceRequired.prototype.addRequiredPolicies = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.pb.PolicyAcceptanceRequired.RequiredPolicyInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.pb.PolicyAcceptanceRequired} returns this
 */
proto.pb.PolicyAcceptanceRequired.prototype.clearRequiredPoliciesList = function() {
  return this.setRequiredPoliciesList([]);
};


goog.object.extend(exports, proto.pb);
