import * as jspb from 'google-protobuf'

import * as google_api_annotations_pb from './google/api/annotations_pb'; // proto import: "google/api/annotations.proto"
import * as rpc_resend_verification_email_pb from './rpc_resend_verification_email_pb'; // proto import: "rpc_resend_verification_email.proto"
import * as protoc$gen$openapiv2_options_annotations_pb from './protoc-gen-openapiv2/options/annotations_pb'; // proto import: "protoc-gen-openapiv2/options/annotations.proto"
import * as rpc_reset_password_pb from './rpc_reset_password_pb'; // proto import: "rpc_reset_password.proto"
import * as rpc_token_product_pb from './rpc_token_product_pb'; // proto import: "rpc_token_product.proto"
import * as rpc_file_system_pb from './rpc_file_system_pb'; // proto import: "rpc_file_system.proto"
import * as rpc_user_pb from './rpc_user_pb'; // proto import: "rpc_user.proto"
import * as rpc_login_user_pb from './rpc_login_user_pb'; // proto import: "rpc_login_user.proto"
import * as rpc_verify_email_pb from './rpc_verify_email_pb'; // proto import: "rpc_verify_email.proto"
import * as rpc_refresh_token_pb from './rpc_refresh_token_pb'; // proto import: "rpc_refresh_token.proto"
import * as rpc_authorize_user_pb from './rpc_authorize_user_pb'; // proto import: "rpc_authorize_user.proto"
import * as rpc_country_pb from './rpc_country_pb'; // proto import: "rpc_country.proto"
import * as rpc_resort_pb from './rpc_resort_pb'; // proto import: "rpc_resort.proto"
import * as rpc_forget_password_pb from './rpc_forget_password_pb'; // proto import: "rpc_forget_password.proto"
import * as rpc_certificate_type_pb from './rpc_certificate_type_pb'; // proto import: "rpc_certificate_type.proto"
import * as rpc_instructor_pb from './rpc_instructor_pb'; // proto import: "rpc_instructor.proto"
import * as rpc_instructor_certificate_pb from './rpc_instructor_certificate_pb'; // proto import: "rpc_instructor_certificate.proto"
import * as rpc_token_system_pb from './rpc_token_system_pb'; // proto import: "rpc_token_system.proto"
import * as rpc_chat_system_pb from './rpc_chat_system_pb'; // proto import: "rpc_chat_system.proto"
import * as rpc_lesson_pb from './rpc_lesson_pb'; // proto import: "rpc_lesson.proto"
import * as rpc_code_pb from './rpc_code_pb'; // proto import: "rpc_code.proto"
import * as rpc_review_pb from './rpc_review_pb'; // proto import: "rpc_review.proto"
import * as rpc_policy_pb from './rpc_policy_pb'; // proto import: "rpc_policy.proto"
import * as rpc_delete_file_pb from './rpc_delete_file_pb'; // proto import: "rpc_delete_file.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


